server:
  port: 8080

spring:
  application:
    name: product-manager

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9192/realms/yt-dev
          jwk-set-uri: http://localhost:9192/realms/yt-dev/protocol/openid-connect/certs



